---
kind: pipeline
name: test

steps:
  - name: lint
    image: golang
    pull: always
    commands:
      - find . -name "*.go" | xargs gofmt -s -d
      #- go vet ./...
    when:
      event:
        - push
        - tag

  - name: build-linux-push
    group: build
    image: golang
    pull: always
    depends_on:
      - lint
    environment:
      GOOS: linux
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go mod vendor
      - go build
    when:
      event:
        - push

  - name: build-darwin-push
    group: build
    image: golang
    pull: always
    depends_on:
      - lint
    environment:
      GOOS: darwin
      GOARCH: amd64
      CGO_ENABLED: 0
    commands:
      - go mod vendor
      - go build
    when:
      event:
        - push

  - name: build-release-homebrew
    image: goreleaser/goreleaser:v0.124
    pull: always
    environment:
      GITHUB_TOKEN:
        from_secret: GITHUB_TOKEN
    secrets:
      - GITHUB_TOKEN
    commands:
      - goreleaser --skip-validate
    when:
      event: push
